---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: valkey/valkey:alpine3.22
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: valkey-nodeport
  namespace: valkey
spec:
  type: NodePort
  selector:
    app: valkey
  ports:
    - port: 6379        # internal container port
      targetPort: 6379
      nodePort: 30079   # expose`d port on all nodes